#! /bin/bash
#run some test for the program
#to be added


TEST_NAME=ping_test

echo "==========Ping Test =========="

CUR_DIR=$(pwd)
SLEEP_TIME=8
SECONDARIES_SIZE=1

#do not re-compile
:<<'END'
cd ..
make clean 
make
cd ${CUR_DIR}
END

if [ ! -e ${CUR_DIR}/${TEST_NAME} ];then
    FILEPATH=${CUR_DIR}/test
else
    FILEPATH=${CUR_DIR}
fi

if [ ! -e ${FILEPATH}/${TEST_NAME} ];then
    echo ${CUR_DIR}
    echo ${FILEPATH}
    echo "Script Execution Path Error"
    exit 1
fi


if [ ! -d ${FILEPATH}/log ];then
    mkdir ${FILEPATH}/log
fi

exec 2>${FILEPATH}/log/ping_test_err

export LD_LIBRARY_PATH=${FILEPATH}/../.local/lib

echo "The Log File Will Be Stored In ${FILEPATH}/log/${TEST_NAME}_*"
#echo "Now We Start The Leader"
${FILEPATH}/../server.out -n 0 -m s -c ${FILEPATH}/../nodes.cfg &>${FILEPATH}/log/${TEST_NAME}_0  &
PRIMARY_PID=$!

#echo "Now We Start Other Nodes"

for i in $(seq ${SECONDARIES_SIZE});do
    ${FILEPATH}/../server.out -n ${i} -m r -c ${FILEPATH}/../nodes.cfg &>${FILEPATH}/log/${TEST_NAME}_${i} &
    declare NODE_${i}=$!
done

:<<'DEBUG'
for i in $(echo ${!NODE*});do
    echo "${!i}"
done
DEBUG

#echo "Sleep Some Time"
sleep ${SLEEP_TIME}

#echo "Kill The Leader"
kill ${PRIMARY_PID} &>/dev/null

#echo "Sleep Some Time"
sleep ${SLEEP_TIME}

for i in $(echo ${!NODE*});do
    kill ${!i} &>/dev/null
done

LOG_NAME=${FILEPATH}/log/${TEST_NAME}_1

RESULT=$(grep "Lost.*Leader" ${LOG_NAME} | wc -l)

if [ "${RESULT}" -eq "0"];then
    exit 1
else
    exit 0
fi
