#! /bin/bash
#run some test for the program
#to be added

#start one leader, test whether all the initializations finish


check_output(){
    exit 0
}

TEST_NAME=$(basename $0)
NO=${1}

#echo "==========Node Start Test =========="

CUR_DIR=$(pwd)

LOG_SUFFIX=".log"
SLEEP_TIME=3
SECONDARIES_SIZE=2
#do not re-compile

:<<'END'
cd ..
make clean 
make
cd ${CUR_DIR}
END


if [ ! -e ${CUR_DIR}/${TEST_NAME} ];then
    FILEPATH=${CUR_DIR}/test
else
    FILEPATH=${CUR_DIR}
fi

if [ ! -e ${FILEPATH}/${TEST_NAME} ];then
    echo ${CUR_DIR}
    echo ${FILEPATH}
    echo "Script Execution Path Error"
    exit 1
fi


if [ ! -d ${FILEPATH}/log ];then
    mkdir ${FILEPATH}/log
fi

TEST_DATE=$(date +"%F-%H") 

LOG_PATH=${FILEPATH}/log/${TEST_NAME}-${NO}-${TEST_DATE}

echo ${LOG_PATH}

if [ ! -d ${LOG_PATH} ];then
    mkdir ${LOG_PATH}
fi

read -p haha

exec 2>${LOG_PATH}/script-err${LOG_SUFFIX}

export LD_LIBRARY_PATH=${FILEPATH}/../.local/lib

SERVER_PROGRAM=${FILEPATH}/../target/server.out
CONFIG_FILE=${FILEPATH}/../target/single_server.cfg

rm -rf ${FILEPATH}/.db

#echo "The Log File Will Be Stored In ${FILEPATH}/log/${TEST_NAME}_*_${NO}"
#echo "Now We Start The Leader"
${SERVER_PROGRAM} -n 0 -m s -c ${CONFIG_FILE} -l ${LOG_PATH} 1>${LOG_PATH}/node0-stdout 2>${LOG_PATH}/node0-stderr &

PRIMARY_PID=$!

#echo "Sleep Some Time"

CLIENT_PROGRAM=${FILEPATH}/../client/client.out

#${CLIENT_PROGRAM} -n 0 -s 127.0.0.1 -p 9000 -r 1000  &>/dev/null &
#${CLIENT_PROGRAM} -n 1 -s 127.0.0.1 -p 9000 -r 1000  &>/dev/null &
#${CLIENT_PROGRAM} -n 2 -s 127.0.0.1 -p 9000 -r 1000  &>/dev/null &
#${CLIENT_PROGRAM} -n 3 -s 127.0.0.1 -p 9000 -r 1000  &>/dev/null &
#${CLIENT_PROGRAM} -n 4 -s 127.0.0.1 -p 9000 -r 1000  &>/dev/null &

read -p haha

#echo "Kill The Leader"
kill -15 ${PRIMARY_PID} &>/dev/null
